# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Tibor Auer
email: tibor.auer@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Tibor Auer is a research fellow at the University of Surrey in Guildford. 
  His research interests include brain dynamics in short and long term, 
  as well as developing approaches and tools to facilitate adoption of best practices.
twitter_username: TiborAuer
github_username: tiborauer
minimal_mistakes_skin: air
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/London # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name        : "Tibor Auer"
  bio         : "neuro-imaginer, neurosha(r)per, neurohacker, science opener"
  avatar      : "/assets/images/bio-photo.jpg"
  links:
    - label: "Work Website"
      icon: "fas fa-fw fa-link"
      url: "https://www.surrey.ac.uk/people/tibor-auer"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:tibor.auer@gmail.com"
    - label: "Google Scholar"
      icon: "fab fa-fw fa-google"
      url: "http://scholar.google.co.uk/citations?user=PzLFHjUAAAAJ"
    - label: "ResearchGate"
      icon: "fab fa-fw fa-researchgate"
      url: "https://www.researchgate.net/profile/Tibor_Auer"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/tiborauer"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/tibor-auer-4817571a4/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/TiborAuer"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "http://facebook.com/tibor.auer"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
      classes: wide

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
